import { Poppins } from 'next/font/google';
import Link from 'next/link';
import Image from 'next/image'; // Import Image component van Next.js
import ToggleSwitch from '@/components/ToggleSwitch';



import './globals.css';



const poppins = Poppins({
  weight: ['400', '600'], // pas aan naar wat je nodig hebt
  subsets: ['latin'],
  variable: '--font-poppins',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <header>
          {/* Logo boven de navigatie */}
          <div className="logo-container">
            <Link href="/">
              <Image
                src="/logo.svg"
                alt="Mijn App Logo"
                width={210}
                height={110}
              />
            </Link>

            <ToggleSwitch />
          </div>

 
   
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
