import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import Image from 'next/image'; // Import Image component van Next.js

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          {/* Logo boven de navigatie */}
          <div className="logo-container">
            <Link href="/">
              <Image
                src="/logo.svg"
                alt="Mijn App Logo"
                width={210}
                height={110}
              />
            </Link>
          </div>

          {/* Navigatie links */}
          <nav>
             <Link href="/account" className="nav-item">
              <div className="icon-label">
                <img src="account.svg" alt="Likes" />
                <span>Likes</span>
              </div>
            </Link>
            <Link href="/" className="nav-item">
              <div className="icon-label">
                <img src="huisje.svg" alt="Home" />
                <span>Home</span>
              </div>
            </Link>
            <Link href="/likes" className="nav-item">
              <div className="icon-label">
                <img src="hartje.svg" alt="Likes" className="hartje" />
                <span>Likes</span>
              </div>
            </Link>
          </nav>
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
