import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import Image from 'next/image';  // Import Image component van Next.js

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          {/* Logo boven de navigatie */}
          <div className="logo-container">
            <Link href="/">
              <Image 
                src="/logo.svg" 
                alt="Mijn App Logo" 
                width={230} 
                height={130} 
              />
            </Link>
          </div>

          {/* Navigatie links */}
          <nav>
            <Link href="/account">Account</Link>
            <Link href="/">Home</Link>
            <Link href="/about">Likes</Link>
           
          </nav>
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
